import Head from 'next/head'
import DraftBanner from '../components/banner/DraftBanner'
import Header from '../components/header/Header'
import FeaturedProduct from '../components/products/FeaturedProduct'
import featured from '../public/json-files/featured.json'

export default function Home ({ products }) {
  return (
    <div
      className='
    '
    >
      <Head>
        <title>Batt-and-wheels</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/css2?family=Urbanist&display=swap'
        />
      </Head>

      <Header />
      <main
        className='
      max-w-screen-2xl 
      mx-auto 
      scrollbar-hide'
      >
        <DraftBanner />
        <div className='productFeed'>
          {/**featured */}
          {featured
            .slice(0, 4)
            .map(({ title, description, category, img, price }) => (
              <FeaturedProduct
                key={img}
                title={title}
                description={description}
                category={category}
                img={img}
                price={price}
              />
            ))}
          <img
            src='https://links.papareact.com/dyz'
            alt=''
            className='md:col-span-full'
          />
          <div className='md:col-span-2'>
            {featured
              .slice(4, 5)
              .map(({ title, description, category, img, price }) => (
                <FeaturedProduct
                  key={img}
                  title={title}
                  description={description}
                  category={category}
                  img={img}
                  price={price}
                />
              ))}
          </div>
          {featured
            .slice(5, featured.length)
            .map(({ title, description, category, img, price }) => (
              <FeaturedProduct
                key={img}
                title={title}
                description={description}
                category={category}
                img={img}
                price={price}
              />
            ))}
        </div>
      </main>
    </div>
  )
}

export async function getServerSideProps () {
  const products = await fetch('https://fakestoreapi.com/products').then(res =>
    res.json()
  )
  return {
    props: {
      products
    }
  }
}
