import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner/Banner'
import DraftBanner from '../components/banner/DraftBanner'
import Header from '../components/header/Header'
import ProductFeed from '../components/products/ProductFeed'

export default function Home ({ products }) {
  return (
    <div
      className='
    '
    >
      <Head>
        <title>Batt-and-wheels</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/css2?family=Urbanist&display=swap'
        />
      </Head>

      <Header />
      <main
        className='
      max-w-screen-2xl 
      mx-auto 
      scrollbar-hide'
      >
        <DraftBanner />
        <ProductFeed products={products} />
      </main>
    </div>
  )
}

export async function getServerSideProps () {
  const products = await fetch('https://fakestoreapi.com/products').then(res =>
    res.json()
  )
  return {
    props: {
      products
    }
  }
}
