import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner/Banner'
import Header from '../components/header/Header'

export default function Home () {
  return (
    <div>
      <Head>
        <title>Batt-and-wheels</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/css2?family=Urbanist&display=swap'
        />
      </Head>

      <Header />
      <main className='max-w-screen-2xl mx-auto'>
        <Banner />
      </main>
    </div>
  )
}
